spring:
  datasource:
    # TODO 开发使用绝对路径,打包部署使用相对路径
    # url: jdbc:sqlite::resource:database/FileSync.db
    url: jdbc:sqlite:src/main/resources/database/FileSync.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 7000

logging:
  file:
    path: log

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com/example/filesync/entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl